#!/bin/bash

echo "In python_rust_caller.lsf"

ml anaconda3
source /hpc/packages/minerva-centos7/anaconda3/2018.12/etc/profile.d/conda.sh
conda activate general_3.9

base_directory=$1
counter=$2

params="-base_directory $base_directory -counter $counter"

cdir=/sc/arion/work/thomam32/WorkingDir/rust_projects_on_Minerva/immunogenicity_rust/for_CFIT

/hpc/users/thomam32/.conda/envs/general_3.9/bin/python3.9 $cdir/assemble_Imm_dicts.py $params
