#!/bin/bash

echo "In python_rust_caller.lsf"

ml anaconda3
source /hpc/packages/minerva-centos7/anaconda3/2018.12/etc/profile.d/conda.sh
conda activate general_3.9

inclusive_start_ind=$1
inclusive_end_ind=$2

cdir=/sc/arion/work/thomam32/WorkingDir/rust_projects_on_Minerva/immunogenicity_rust/for_Martas_all_IEDB_TESLA/
################################################################################

# neo_hla_tuples_csv="/sc/arion/projects/FLAI/marcus/MARTA_ALL_IEDB_TESLA_ninemers_HLAs/sorted_imm_iedb_tesla_from_Marta.csv"
# save_pkl_dir="/sc/arion/projects/FLAI/marcus/MARTA_IEDB_TESLA_Rust_Results/Immunogenic"
neo_hla_tuples_csv="/sc/arion/projects/FLAI/marcus/MARTA_ALL_IEDB_TESLA_ninemers_HLAs/sorted_nonimm_iedb_tesla_from_Marta.csv"
save_pkl_dir="/sc/arion/projects/FLAI/marcus/MARTA_IEDB_TESLA_Rust_Results/nonImmunogenic"

params="-inclusive_start_ind $inclusive_start_ind -inclusive_end_ind $inclusive_end_ind -neo_hla_tuples_csv $neo_hla_tuples_csv -save_pkl_dir $save_pkl_dir"
/hpc/users/thomam32/.conda/envs/general_3.9/bin/python3.9 $cdir/modeling_immunogenicity_Marta_IEDB_TESLA_Epitopes.py $params
